# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 640))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 10, 35)")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMouseTracking(False)
        self.centralWidget.setObjectName("centralWidget")
        self.fileBrowserWindow = QtWidgets.QGroupBox(self.centralWidget)
        self.fileBrowserWindow.setGeometry(QtCore.QRect(10, 10, 460, 622))
        self.fileBrowserWindow.setMinimumSize(QtCore.QSize(460, 622))
        self.fileBrowserWindow.setMaximumSize(QtCore.QSize(460, 622))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fileBrowserWindow.setFont(font)
        self.fileBrowserWindow.setStyleSheet("color: rgb(0, 187, 255);")
        self.fileBrowserWindow.setFlat(True)
        self.fileBrowserWindow.setObjectName("fileBrowserWindow")
        self.treeView = QtWidgets.QTreeView(self.fileBrowserWindow)
        self.treeView.setGeometry(QtCore.QRect(10, 30, 440, 550))
        self.treeView.setMinimumSize(QtCore.QSize(440, 550))
        self.treeView.setMaximumSize(QtCore.QSize(440, 550))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.treeView.setFont(font)
        self.treeView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.treeView.setAcceptDrops(True)
        self.treeView.setStyleSheet("background-color: rgb(10, 20, 50)")
        self.treeView.setFrameShape(QtWidgets.QFrame.Box)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.treeView.setSortingEnabled(True)
        self.treeView.setAnimated(True)
        self.treeView.setObjectName("treeView")
        self.dodaj = QtWidgets.QPushButton(self.fileBrowserWindow)
        self.dodaj.setGeometry(QtCore.QRect(423, 590, 28, 28))
        self.dodaj.setMinimumSize(QtCore.QSize(28, 28))
        self.dodaj.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dodaj.setFont(font)
        self.dodaj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dodaj.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Grafiki/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Grafiki/add.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.dodaj.setIcon(icon)
        self.dodaj.setObjectName("dodaj")
        self.ciemny = QtWidgets.QPushButton(self.fileBrowserWindow)
        self.ciemny.setGeometry(QtCore.QRect(10, 590, 80, 28))
        self.ciemny.setMinimumSize(QtCore.QSize(80, 28))
        self.ciemny.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ciemny.setFont(font)
        self.ciemny.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ciemny.setStyleSheet("border-color: rgb(0, 187, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Grafiki/Motyw-on.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ciemny.setIcon(icon1)
        self.ciemny.setIconSize(QtCore.QSize(40, 10))
        self.ciemny.setObjectName("ciemny")
        self.jasny = QtWidgets.QPushButton(self.fileBrowserWindow)
        self.jasny.setGeometry(QtCore.QRect(100, 590, 80, 28))
        self.jasny.setMinimumSize(QtCore.QSize(80, 28))
        self.jasny.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jasny.setFont(font)
        self.jasny.setFocusPolicy(QtCore.Qt.NoFocus)
        self.jasny.setStyleSheet("border-color: rgb(0, 187, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Grafiki/Motyw-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.jasny.setIcon(icon2)
        self.jasny.setIconSize(QtCore.QSize(40, 10))
        self.jasny.setObjectName("jasny")
        self.odtwarzanie = QtWidgets.QGroupBox(self.centralWidget)
        self.odtwarzanie.setGeometry(QtCore.QRect(490, 10, 500, 191))
        self.odtwarzanie.setMinimumSize(QtCore.QSize(500, 191))
        self.odtwarzanie.setMaximumSize(QtCore.QSize(500, 191))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.odtwarzanie.setFont(font)
        self.odtwarzanie.setStyleSheet("color: rgb(0,187, 255);")
        self.odtwarzanie.setFlat(True)
        self.odtwarzanie.setObjectName("odtwarzanie")
        self.mute = QtWidgets.QPushButton(self.odtwarzanie)
        self.mute.setGeometry(QtCore.QRect(465, 160, 28, 28))
        self.mute.setMinimumSize(QtCore.QSize(28, 28))
        self.mute.setMaximumSize(QtCore.QSize(28, 28))
        self.mute.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mute.setAutoFillBackground(False)
        self.mute.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Grafiki/Speaker-mowp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("Grafiki/Mute-mowp.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("Grafiki/Mute-mowp.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.mute.setIcon(icon3)
        self.mute.setObjectName("mute")
        self.volumeControl = QtWidgets.QSlider(self.odtwarzanie)
        self.volumeControl.setGeometry(QtCore.QRect(470, 50, 21, 101))
        self.volumeControl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volumeControl.setProperty("value", 99)
        self.volumeControl.setOrientation(QtCore.Qt.Vertical)
        self.volumeControl.setInvertedControls(False)
        self.volumeControl.setObjectName("volumeControl")
        self.pasekPostepu = QtWidgets.QSlider(self.odtwarzanie)
        self.pasekPostepu.setGeometry(QtCore.QRect(10, 114, 440, 16))
        self.pasekPostepu.setMinimumSize(QtCore.QSize(440, 16))
        self.pasekPostepu.setMaximumSize(QtCore.QSize(440, 16))
        self.pasekPostepu.setMouseTracking(True)
        self.pasekPostepu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pasekPostepu.setStyleSheet("")
        self.pasekPostepu.setMaximum(100)
        self.pasekPostepu.setOrientation(QtCore.Qt.Horizontal)
        self.pasekPostepu.setInvertedAppearance(False)
        self.pasekPostepu.setTickInterval(0)
        self.pasekPostepu.setObjectName("pasekPostepu")
        self.groupBox = QtWidgets.QGroupBox(self.odtwarzanie)
        self.groupBox.setGeometry(QtCore.QRect(260, 130, 191, 51))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 181, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.powtarzanie = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.powtarzanie.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.powtarzanie.setContentsMargins(11, 11, 11, 11)
        self.powtarzanie.setSpacing(2)
        self.powtarzanie.setObjectName("powtarzanie")
        self.brakRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.brakRadio.setMinimumSize(QtCore.QSize(50, 20))
        self.brakRadio.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setWeight(50)
        self.brakRadio.setFont(font)
        self.brakRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.brakRadio.setAutoFillBackground(False)
        self.brakRadio.setStyleSheet("")
        self.brakRadio.setChecked(True)
        self.brakRadio.setObjectName("brakRadio")
        self.powtarzanie.addWidget(self.brakRadio)
        self.utworRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.utworRadio.setMinimumSize(QtCore.QSize(50, 20))
        self.utworRadio.setMaximumSize(QtCore.QSize(50, 20))
        self.utworRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Grafiki/repeat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.utworRadio.setIcon(icon4)
        self.utworRadio.setObjectName("utworRadio")
        self.powtarzanie.addWidget(self.utworRadio)
        self.listaRadio = QtWidgets.QRadioButton(self.layoutWidget)
        self.listaRadio.setMinimumSize(QtCore.QSize(62, 20))
        self.listaRadio.setMaximumSize(QtCore.QSize(26, 20))
        self.listaRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listaRadio.setIcon(icon4)
        self.listaRadio.setObjectName("listaRadio")
        self.powtarzanie.addWidget(self.listaRadio)
        self.label_2 = QtWidgets.QLabel(self.odtwarzanie)
        self.label_2.setGeometry(QtCore.QRect(463, 30, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.informacje = QtWidgets.QGroupBox(self.odtwarzanie)
        self.informacje.setGeometry(QtCore.QRect(10, 30, 440, 80))
        self.informacje.setMinimumSize(QtCore.QSize(440, 80))
        self.informacje.setMaximumSize(QtCore.QSize(440, 80))
        self.informacje.setStyleSheet("background-color: rgb(0, 0, 18);")
        self.informacje.setTitle("")
        self.informacje.setFlat(True)
        self.informacje.setObjectName("informacje")
        self.label_3 = QtWidgets.QLabel(self.informacje)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.informacje)
        self.label.setGeometry(QtCore.QRect(10, 50, 52, 23))
        self.label.setMinimumSize(QtCore.QSize(52, 0))
        self.label.setMaximumSize(QtCore.QSize(52, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.czasCalkowity = QtWidgets.QLabel(self.informacje)
        self.czasCalkowity.setGeometry(QtCore.QRect(60, 50, 60, 23))
        self.czasCalkowity.setMinimumSize(QtCore.QSize(60, 0))
        self.czasCalkowity.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.czasCalkowity.setFont(font)
        self.czasCalkowity.setObjectName("czasCalkowity")
        self.previous = QtWidgets.QPushButton(self.odtwarzanie)
        self.previous.setGeometry(QtCore.QRect(12, 141, 36, 28))
        self.previous.setMinimumSize(QtCore.QSize(36, 28))
        self.previous.setMaximumSize(QtCore.QSize(36, 28))
        self.previous.setFocusPolicy(QtCore.Qt.NoFocus)
        self.previous.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Grafiki/rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap("Grafiki/rewind.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.previous.setIcon(icon5)
        self.previous.setObjectName("previous")
        self.playPause = QtWidgets.QPushButton(self.odtwarzanie)
        self.playPause.setGeometry(QtCore.QRect(51, 141, 36, 28))
        self.playPause.setMinimumSize(QtCore.QSize(36, 28))
        self.playPause.setMaximumSize(QtCore.QSize(36, 28))
        self.playPause.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playPause.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Grafiki/playArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap("Grafiki/pause.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.playPause.setIcon(icon6)
        self.playPause.setFlat(False)
        self.playPause.setObjectName("playPause")
        self.next = QtWidgets.QPushButton(self.odtwarzanie)
        self.next.setGeometry(QtCore.QRect(90, 141, 36, 28))
        self.next.setMinimumSize(QtCore.QSize(36, 28))
        self.next.setMaximumSize(QtCore.QSize(36, 28))
        self.next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.next.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Grafiki/rewind2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap("Grafiki/rewind2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.next.setIcon(icon7)
        self.next.setObjectName("next")
        self.stop = QtWidgets.QPushButton(self.odtwarzanie)
        self.stop.setGeometry(QtCore.QRect(129, 141, 36, 28))
        self.stop.setMaximumSize(QtCore.QSize(36, 28))
        self.stop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Grafiki/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon8)
        self.stop.setObjectName("stop")
        self.random = QtWidgets.QPushButton(self.odtwarzanie)
        self.random.setGeometry(QtCore.QRect(168, 141, 36, 28))
        self.random.setMinimumSize(QtCore.QSize(36, 28))
        self.random.setMaximumSize(QtCore.QSize(36, 28))
        self.random.setFocusPolicy(QtCore.Qt.NoFocus)
        self.random.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Grafiki/shuffleOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random.setIcon(icon9)
        self.random.setIconSize(QtCore.QSize(22, 22))
        self.random.setObjectName("random")
        self.playlistWindow = QtWidgets.QGroupBox(self.centralWidget)
        self.playlistWindow.setGeometry(QtCore.QRect(490, 220, 500, 413))
        self.playlistWindow.setMinimumSize(QtCore.QSize(0, 413))
        self.playlistWindow.setMaximumSize(QtCore.QSize(16777215, 413))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.playlistWindow.setFont(font)
        self.playlistWindow.setStyleSheet("color: rgb(0, 187, 255);")
        self.playlistWindow.setFlat(True)
        self.playlistWindow.setObjectName("playlistWindow")
        self.playlista = QtWidgets.QListView(self.playlistWindow)
        self.playlista.setGeometry(QtCore.QRect(10, 30, 480, 340))
        self.playlista.setMinimumSize(QtCore.QSize(480, 340))
        self.playlista.setMaximumSize(QtCore.QSize(480, 340))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.playlista.setFont(font)
        self.playlista.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playlista.setAcceptDrops(True)
        self.playlista.setStyleSheet("background-color: rgb(10, 20, 50)")
        self.playlista.setFrameShape(QtWidgets.QFrame.Box)
        self.playlista.setDragEnabled(True)
        self.playlista.setDragDropOverwriteMode(True)
        self.playlista.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.playlista.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.playlista.setObjectName("playlista")
        self.trackUp = QtWidgets.QPushButton(self.playlistWindow)
        self.trackUp.setGeometry(QtCore.QRect(11, 380, 28, 28))
        self.trackUp.setMinimumSize(QtCore.QSize(28, 28))
        self.trackUp.setMaximumSize(QtCore.QSize(28, 28))
        self.trackUp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.trackUp.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Grafiki/arrow-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon10.addPixmap(QtGui.QPixmap("Grafiki/arrow-up.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.trackUp.setIcon(icon10)
        self.trackUp.setObjectName("trackUp")
        self.trackDown = QtWidgets.QPushButton(self.playlistWindow)
        self.trackDown.setGeometry(QtCore.QRect(45, 380, 28, 28))
        self.trackDown.setMinimumSize(QtCore.QSize(28, 28))
        self.trackDown.setMaximumSize(QtCore.QSize(28, 28))
        self.trackDown.setFocusPolicy(QtCore.Qt.NoFocus)
        self.trackDown.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Grafiki/arrow-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon11.addPixmap(QtGui.QPixmap("Grafiki/arrow-down.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.trackDown.setIcon(icon11)
        self.trackDown.setObjectName("trackDown")
        self.remove = QtWidgets.QPushButton(self.playlistWindow)
        self.remove.setGeometry(QtCore.QRect(79, 380, 28, 28))
        self.remove.setMinimumSize(QtCore.QSize(28, 28))
        self.remove.setMaximumSize(QtCore.QSize(28, 28))
        self.remove.setFocusPolicy(QtCore.Qt.NoFocus)
        self.remove.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Grafiki/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap("Grafiki/remove.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.remove.setIcon(icon12)
        self.remove.setObjectName("remove")
        self.wczytaj = QtWidgets.QPushButton(self.playlistWindow)
        self.wczytaj.setGeometry(QtCore.QRect(321, 380, 80, 28))
        self.wczytaj.setMinimumSize(QtCore.QSize(80, 28))
        self.wczytaj.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wczytaj.setFont(font)
        self.wczytaj.setFocusPolicy(QtCore.Qt.NoFocus)
        self.wczytaj.setStyleSheet("border-color: rgb(0, 187, 255);")
        self.wczytaj.setObjectName("wczytaj")
        self.zapisz = QtWidgets.QPushButton(self.playlistWindow)
        self.zapisz.setGeometry(QtCore.QRect(411, 380, 80, 28))
        self.zapisz.setMinimumSize(QtCore.QSize(80, 28))
        self.zapisz.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.zapisz.setFont(font)
        self.zapisz.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zapisz.setStyleSheet("")
        self.zapisz.setObjectName("zapisz")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(469, 0, 21, 641))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(480, 200, 511, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Music on Window Player"))
        self.fileBrowserWindow.setTitle(_translate("MainWindow", "Przeglądarka plików "))
        self.dodaj.setToolTip(_translate("MainWindow", "Dodaj plik/katalog do listy odtwarzania"))
        self.ciemny.setToolTip(_translate("MainWindow", "Przełącz na ciemny motyw"))
        self.ciemny.setText(_translate("MainWindow", "Ciemny"))
        self.jasny.setToolTip(_translate("MainWindow", "Przełącz na ciemny motyw"))
        self.jasny.setText(_translate("MainWindow", "Jasny"))
        self.odtwarzanie.setTitle(_translate("MainWindow", "Odtwarzanie "))
        self.mute.setToolTip(_translate("MainWindow", "Wycisz/włącz dźwięk"))
        self.mute.setShortcut(_translate("MainWindow", "M"))
        self.groupBox.setTitle(_translate("MainWindow", "Powtarzanie"))
        self.brakRadio.setToolTip(_translate("MainWindow", "Brak powtarzania"))
        self.brakRadio.setText(_translate("MainWindow", "Brak"))
        self.utworRadio.setToolTip(_translate("MainWindow", "Powtarzanie jednego utworu"))
        self.utworRadio.setText(_translate("MainWindow", "1"))
        self.listaRadio.setToolTip(_translate("MainWindow", "Powtarzanie listy odtwarzania"))
        self.listaRadio.setText(_translate("MainWindow", "ALL"))
        self.label_2.setText(_translate("MainWindow", "100%"))
        self.label_3.setText(_translate("MainWindow", "Jakiś całkiem długi tytuł z rozszerzeniem.flac"))
        self.label.setText(_translate("MainWindow", "00:00"))
        self.czasCalkowity.setText(_translate("MainWindow", "/ 00:00"))
        self.previous.setToolTip(_translate("MainWindow", "Przewiń do tyłu"))
        self.previous.setShortcut(_translate("MainWindow", "Backspace, Backspace, Backspace"))
        self.playPause.setToolTip(_translate("MainWindow", "Odtwarzanie/pauza"))
        self.playPause.setShortcut(_translate("MainWindow", "Space"))
        self.next.setToolTip(_translate("MainWindow", "Przewiń do przodu"))
        self.next.setShortcut(_translate("MainWindow", "Right"))
        self.stop.setToolTip(_translate("MainWindow", "Zatrzymaj"))
        self.stop.setShortcut(_translate("MainWindow", "S"))
        self.random.setToolTip(_translate("MainWindow", "Włącz/wyłącz odtwarzanie losowe"))
        self.random.setShortcut(_translate("MainWindow", "R"))
        self.playlistWindow.setTitle(_translate("MainWindow", "Lista odtwarzania "))
        self.trackUp.setToolTip(_translate("MainWindow", "Przesuń utwór o pozycję w górę na liście odtwarzania"))
        self.trackDown.setToolTip(_translate("MainWindow", "Przesuń utwór o pozycję w dół na liście odtwarzania"))
        self.remove.setToolTip(_translate("MainWindow", "Usuń utwór z listy odtwarzania"))
        self.wczytaj.setToolTip(_translate("MainWindow", "Wczytaj zapisaną listę odtwarzania"))
        self.wczytaj.setText(_translate("MainWindow", "Wczytaj"))
        self.zapisz.setToolTip(_translate("MainWindow", "Zapisz aktualną listę odtwarzania"))
        self.zapisz.setText(_translate("MainWindow", "Zapisz"))
        self.zapisz.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

