# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 640))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setMouseTracking(False)
        self.centralWidget.setObjectName("centralWidget")
        self.fieleBrowserWindow = QtWidgets.QGroupBox(self.centralWidget)
        self.fieleBrowserWindow.setGeometry(QtCore.QRect(10, 10, 461, 621))
        self.fieleBrowserWindow.setFlat(True)
        self.fieleBrowserWindow.setObjectName("fieleBrowserWindow")
        self.treeView = QtWidgets.QTreeView(self.fieleBrowserWindow)
        self.treeView.setGeometry(QtCore.QRect(0, 20, 461, 601))
        self.treeView.setObjectName("treeView")
        self.odtwarzanie = QtWidgets.QGroupBox(self.centralWidget)
        self.odtwarzanie.setGeometry(QtCore.QRect(490, 10, 501, 191))
        self.odtwarzanie.setFlat(True)
        self.odtwarzanie.setObjectName("odtwarzanie")
        self.layoutWidget = QtWidgets.QWidget(self.odtwarzanie)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 160, 251, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.kontrola = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.kontrola.setContentsMargins(11, 11, 11, 11)
        self.kontrola.setSpacing(2)
        self.kontrola.setObjectName("kontrola")
        self.previous = QtWidgets.QPushButton(self.layoutWidget)
        self.previous.setFocusPolicy(QtCore.Qt.NoFocus)
        self.previous.setObjectName("previous")
        self.kontrola.addWidget(self.previous)
        self.playPause = QtWidgets.QPushButton(self.layoutWidget)
        self.playPause.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playPause.setFlat(False)
        self.playPause.setObjectName("playPause")
        self.kontrola.addWidget(self.playPause)
        self.next = QtWidgets.QPushButton(self.layoutWidget)
        self.next.setFocusPolicy(QtCore.Qt.NoFocus)
        self.next.setObjectName("next")
        self.kontrola.addWidget(self.next)
        self.stop = QtWidgets.QPushButton(self.layoutWidget)
        self.stop.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop.setObjectName("stop")
        self.kontrola.addWidget(self.stop)
        self.random = QtWidgets.QPushButton(self.layoutWidget)
        self.random.setFocusPolicy(QtCore.Qt.NoFocus)
        self.random.setObjectName("random")
        self.kontrola.addWidget(self.random)
        self.mute = QtWidgets.QPushButton(self.odtwarzanie)
        self.mute.setGeometry(QtCore.QRect(470, 160, 28, 28))
        self.mute.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mute.setObjectName("mute")
        self.volumeControl = QtWidgets.QSlider(self.odtwarzanie)
        self.volumeControl.setGeometry(QtCore.QRect(470, 50, 21, 101))
        self.volumeControl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volumeControl.setProperty("value", 99)
        self.volumeControl.setOrientation(QtCore.Qt.Vertical)
        self.volumeControl.setInvertedControls(False)
        self.volumeControl.setObjectName("volumeControl")
        self.pasekPostepu = QtWidgets.QSlider(self.odtwarzanie)
        self.pasekPostepu.setGeometry(QtCore.QRect(10, 120, 451, 16))
        self.pasekPostepu.setMouseTracking(True)
        self.pasekPostepu.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pasekPostepu.setOrientation(QtCore.Qt.Horizontal)
        self.pasekPostepu.setInvertedAppearance(False)
        self.pasekPostepu.setTickInterval(0)
        self.pasekPostepu.setObjectName("pasekPostepu")
        self.groupBox = QtWidgets.QGroupBox(self.odtwarzanie)
        self.groupBox.setGeometry(QtCore.QRect(280, 140, 181, 51))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(0, 20, 181, 23))
        self.widget.setObjectName("widget")
        self.powtarzanie = QtWidgets.QHBoxLayout(self.widget)
        self.powtarzanie.setContentsMargins(11, 11, 11, 11)
        self.powtarzanie.setSpacing(6)
        self.powtarzanie.setObjectName("powtarzanie")
        self.brakRadio = QtWidgets.QRadioButton(self.widget)
        self.brakRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.brakRadio.setChecked(True)
        self.brakRadio.setObjectName("brakRadio")
        self.powtarzanie.addWidget(self.brakRadio)
        self.utworRadio = QtWidgets.QRadioButton(self.widget)
        self.utworRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.utworRadio.setObjectName("utworRadio")
        self.powtarzanie.addWidget(self.utworRadio)
        self.listaRadio = QtWidgets.QRadioButton(self.widget)
        self.listaRadio.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listaRadio.setObjectName("listaRadio")
        self.powtarzanie.addWidget(self.listaRadio)
        self.label_2 = QtWidgets.QLabel(self.odtwarzanie)
        self.label_2.setGeometry(QtCore.QRect(460, 30, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.odtwarzanie)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 401, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget1 = QtWidgets.QWidget(self.odtwarzanie)
        self.widget1.setGeometry(QtCore.QRect(10, 70, 131, 41))
        self.widget1.setObjectName("widget1")
        self.czasy = QtWidgets.QHBoxLayout(self.widget1)
        self.czasy.setContentsMargins(11, 11, 11, 11)
        self.czasy.setSpacing(6)
        self.czasy.setObjectName("czasy")
        self.label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.czasy.addWidget(self.label)
        self.czasCalkowity = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(17)
        self.czasCalkowity.setFont(font)
        self.czasCalkowity.setObjectName("czasCalkowity")
        self.czasy.addWidget(self.czasCalkowity)
        self.playlistWindow = QtWidgets.QGroupBox(self.centralWidget)
        self.playlistWindow.setGeometry(QtCore.QRect(490, 220, 501, 411))
        self.playlistWindow.setFlat(True)
        self.playlistWindow.setObjectName("playlistWindow")
        self.listView = QtWidgets.QListView(self.playlistWindow)
        self.listView.setGeometry(QtCore.QRect(0, 20, 501, 391))
        self.listView.setObjectName("listView")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(469, 0, 21, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(480, 200, 511, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fieleBrowserWindow.setTitle(_translate("MainWindow", "Przeglądarka plików "))
        self.odtwarzanie.setTitle(_translate("MainWindow", "Odtwarzanie "))
        self.previous.setText(_translate("MainWindow", "Pr"))
        self.playPause.setText(_translate("MainWindow", "P"))
        self.next.setText(_translate("MainWindow", "Nx"))
        self.stop.setText(_translate("MainWindow", "S"))
        self.random.setText(_translate("MainWindow", "R"))
        self.mute.setText(_translate("MainWindow", "M"))
        self.groupBox.setTitle(_translate("MainWindow", "Powtarzanie"))
        self.brakRadio.setText(_translate("MainWindow", "Brak"))
        self.utworRadio.setText(_translate("MainWindow", "Utwór"))
        self.listaRadio.setText(_translate("MainWindow", "Lista"))
        self.label_2.setText(_translate("MainWindow", "100%"))
        self.label_3.setText(_translate("MainWindow", "Jakiś całkiem długi tytuł z rozszerzeniem.flac"))
        self.label.setText(_translate("MainWindow", "00:00"))
        self.czasCalkowity.setText(_translate("MainWindow", "/00:00"))
        self.playlistWindow.setTitle(_translate("MainWindow", "Lista odtwarzania "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

